version: "1.0"
info:
  model: int-scaffold
packages:
- name: May23ExternalProjectProject
  gitServerName: ExternalGitProject
  gitUrl: https://github.com/Kruthika-K-IBM
  gitUsername: Kruthika-K-IBM
  gitBranch: main
